[phases.setup]
nixPkgs = ["python3", "pip", "gcc", "libjpeg", "zlib", "freetype", "lcms2", "openjpeg", "libtiff", "tk"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python wsgi.py"
